development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: first_app
  pool:     5
  username: enbake
  password: enbake

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: first_app
  pool:     5
  username: enbake
  password: enbake

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: first_app
  pool:     5
  username: enbake
  password: enbake